import { useState } from 'react';

import { Button } from '@/components/ui/Button';
import { Surface } from '@/components/ui/Surface';
import { summarizeSpecBudget, validateIssueReadiness } from '@/lib/specforge/domain';
import type { SpecForgeAggregate } from '@/lib/specforge/types';
import type { RoleKey } from '@/lib/types';

const money = (value: number) => `R ${value.toLocaleString('en-ZA', { maximumFractionDigits: 0 })}`;
const status = (value: string) => <span className={`specforge-status specforge-status--${value}`}>{value.replaceAll('_',' ')}</span>;
const cssImage = (url: string) => `url("${url.replaceAll('\\', '%5C').replaceAll('"', '%22')}")`;

interface Props {
  tab: string;
  workspace: SpecForgeAggregate;
  role: RoleKey;
  canEdit: boolean;
  onDuplicate: (itemId: string) => Promise<unknown>;
  onDecide: (approvalId: string, decision: 'approved' | 'rejected') => Promise<unknown>;
  onValidateIssue: () => Promise<{ ready: boolean; codes: string[] }>;
  onIssue: (input: { title: string; audience: string }) => Promise<unknown>;
  onDrawingScan: (drawingRevisionId: string) => Promise<unknown>;
}

export function SpecForgeRecords({ tab, workspace, role, canEdit, onDuplicate, onDecide, onValidateIssue, onIssue, onDrawingScan }: Props) {
  const [message, setMessage] = useState<string | null>(null);
  const [drawingRevision, setDrawingRevision] = useState('');
  const budget = summarizeSpecBudget(workspace.items);
  const readiness = validateIssueReadiness(workspace);

  if (tab === 'pictorial') return <div data-tool-tab={tab} className="specforge-pictorial">{workspace.items.map(item => <Surface as="article" level="raised" key={item.id}><div className="specforge-product-image">{item.imageUrl ? <div className="specforge-product-photo" role="img" aria-label={item.title} style={{ backgroundImage: cssImage(item.imageUrl) }} /> : <div><span>{item.finish ?? 'Product image pending'}</span><small>{item.dimensions ?? item.packageName}</small></div>}</div><div className="specforge-product-copy"><div><code>{item.code}</code>{status(item.status)}</div><h2>{item.title}</h2><p>{item.supplier ?? 'Supplier not assigned'} · {item.model ?? 'performance basis'}</p><small>{item.room} · {item.sourceRevision}</small></div></Surface>)}</div>;

  if (tab === 'sections') return <div data-tool-tab={tab} className="specforge-sections">{workspace.sections.map(section => <Surface as="article" level="raised" key={section.id}><header><div><code>{section.code}</code><h2>{section.title}</h2></div>{status(section.status)}</header><p>{section.discipline} · owner {section.ownerRole.replaceAll('_',' ')}</p><div>{workspace.items.filter(item => item.sectionId === section.id).map(item => <span key={item.id}>{item.code} · {item.title}</span>)}</div></Surface>)}</div>;

  if (tab === 'products') return <Surface data-tool-tab={tab} level="raised" className="specforge-table-panel"><div className="specforge-panel__head"><div><span className="specforge-kicker">Controlled records</span><h2>Product register</h2></div><span>{workspace.items.length} visible records</span></div><div className="specforge-table-scroll"><table><thead><tr><th>Reference</th><th>Specification</th><th>Package / room</th><th>Allowance</th><th>Estimate</th><th>Lead</th><th>Status</th><th /></tr></thead><tbody>{workspace.items.map(item => <tr key={item.id}><td><code>{item.code}</code></td><td><strong>{item.title}</strong><small>{item.supplier ?? 'Supplier open'} · {item.finish ?? 'Finish open'}</small></td><td>{item.packageName}<small>{item.room}</small></td><td>{money(item.budgetAllowance)}</td><td>{money(item.estimatedCost)}</td><td>{item.leadTimeDays}d</td><td>{status(item.status)}</td><td>{canEdit && <button type="button" onClick={() => void onDuplicate(item.id)}>Duplicate</button>}</td></tr>)}</tbody></table></div></Surface>;

  if (tab === 'docpreview') return <div data-tool-tab={tab} className="specforge-document-layout"><Surface as="article" level="raised" className="specforge-document"><header><code>{workspace.projectId} · {workspace.revision}</code><h2>Project Works Specification</h2><p>{workspace.projectName} · {workspace.profile}</p></header>{workspace.sections.map(section => <section key={section.id}><span>Section {section.code}</span><h3>{section.title}</h3>{workspace.items.filter(item => item.sectionId === section.id).map(item => <div key={item.id}><h4>{item.code} · {item.title}</h4><p>{item.description}</p><small>Source {item.sourceRevision} · {item.packageName}</small></div>)}</section>)}</Surface><Surface level="inset" className="specforge-document-controls"><span className="specforge-kicker">Live preview</span><h3>Generated from persisted records</h3><p>This preview contains the records visible to your authenticated project role. Issue creates an immutable snapshot.</p><dl><div><dt>Revision</dt><dd>{workspace.revision}</dd></div><div><dt>Sections</dt><dd>{workspace.sections.length}</dd></div><div><dt>Items</dt><dd>{workspace.items.length}</dd></div></dl></Surface></div>;

  if (tab === 'approvals') return <div data-tool-tab={tab} className="specforge-approval-grid">{workspace.approvals.map(approval => <Surface as="article" level="raised" key={approval.id}><div><code>{approval.approvalType}</code>{status(approval.status)}</div><h2>{workspace.items.find(item => item.id === approval.itemId)?.title ?? 'Scoped specification decision'}</h2><p>Requested from {approval.requestedRole.replaceAll('_',' ')}{approval.dueAt ? ` · due ${approval.dueAt}` : ''}</p>{approval.status === 'pending' && (role === approval.requestedRole || role === 'platform_admin') && <footer><Button size="sm" onClick={() => void onDecide(approval.id, 'approved')}>Approve</Button><Button size="sm" variant="danger" onClick={() => void onDecide(approval.id, 'rejected')}>Reject</Button></footer>}</Surface>)}{workspace.approvals.length === 0 && <Empty title="No approval requests" detail="Approval decisions will appear here after an authorized professional requests them." />}</div>;

  if (tab === 'budget') return <div data-tool-tab={tab} className="specforge-budget"><div className="specforge-metrics"><Surface level="raised"><span>Allowance</span><strong>{money(budget.allowance)}</strong></Surface><Surface level="raised"><span>Estimate</span><strong>{money(budget.estimate)}</strong></Surface><Surface level="raised"><span>Variance</span><strong>{money(budget.delta)}</strong></Surface><Surface level="raised"><span>Cost risks</span><strong>{budget.overBudgetItemIds.length}</strong></Surface></div><Surface level="raised" className="specforge-table-panel"><div className="specforge-panel__head"><div><span className="specforge-kicker">QS review</span><h2>Allowance variance</h2></div><span>{workspace.budgetReviewedAt ? `Reviewed ${workspace.budgetReviewedAt}` : 'Review pending'}</span></div>{workspace.items.map(item => <div className="specforge-cost-row" key={item.id}><div><code>{item.code}</code><strong>{item.title}</strong></div><span>{money(item.budgetAllowance)}</span><span>{money(item.estimatedCost)}</span><b className={item.estimatedCost > item.budgetAllowance ? 'is-risk' : ''}>{money(item.estimatedCost - item.budgetAllowance)}</b></div>)}</Surface></div>;

  if (tab === 'bomboq') return <Surface data-tool-tab={tab} level="raised" className="specforge-table-panel"><div className="specforge-panel__head"><div><span className="specforge-kicker">Single source of truth</span><h2>BoM / BoQ linkage</h2></div><span>Specification-derived lines</span></div>{workspace.items.map(item => <div className="specforge-bom-row" key={item.id}><code>{item.code}</code><div><strong>{item.title}</strong><small>{item.packageName}</small></div><span>{money(item.estimatedCost)}</span><span>{item.status === 'issued' ? 'Ready for procurement' : 'Controlled draft'}</span></div>)}</Surface>;

  if (tab === 'drawings') return <div data-tool-tab={tab} className="specforge-drawing-layout"><Surface level="raised" className="specforge-panel"><div className="specforge-panel__head"><div><span className="specforge-kicker">Drawing intelligence</span><h2>Coordination findings</h2></div><span>{workspace.drawingFindings.length} findings</span></div>{workspace.drawingFindings.map(finding => <article className="specforge-finding" key={finding.id}>{status(finding.severity)}<div><strong>{finding.drawingRevisionId}</strong><p>{finding.finding}</p><small>{finding.status} · {finding.itemId ? 'linked item' : 'workspace finding'}</small></div></article>)}{workspace.drawingFindings.length === 0 && <p className="specforge-empty-copy">No drawing findings have been persisted.</p>}</Surface><Surface level="inset" className="specforge-scan-card"><span className="specforge-kicker">Request governed scan</span><h2>Analyse a drawing revision</h2><p>The request creates a queued job. Results remain candidates until professional review.</p><label>Drawing revision ID<input value={drawingRevision} onChange={event => setDrawingRevision(event.target.value)} /></label><Button disabled={!drawingRevision.trim()} onClick={() => void onDrawingScan(drawingRevision.trim()).then(() => setMessage('Drawing scan queued.')).catch(error => setMessage(error instanceof Error ? error.message : 'Scan unavailable.'))}>Request scan</Button>{message && <small role="status">{message}</small>}</Surface></div>;

  if (tab === 'issue') return <div data-tool-tab={tab} className="specforge-issue-layout"><Surface level="raised" className="specforge-panel"><div className="specforge-panel__head"><div><span className="specforge-kicker">Immutable issue history</span><h2>Issue register</h2></div><span>{workspace.issues.length} issues</span></div>{workspace.issues.map(issue => <article className="specforge-issue-row" key={issue.id}><div><code>{issue.revision}</code><strong>{issue.title}</strong><small>{issue.audience} · {issue.issuedAt ?? 'draft'}</small></div>{status(issue.status)}</article>)}{workspace.issues.length === 0 && <p className="specforge-empty-copy">No issue has been created for this workspace.</p>}</Surface><Surface level="inset" className="specforge-issue-gate"><span className="specforge-kicker">Issue gate · {workspace.revision}</span><h2>{readiness.ready ? 'Ready for server validation' : 'Controls require attention'}</h2><p>The server revalidates every gate inside the issue transaction.</p><ul>{readiness.codes.map(code => <li key={code}>{code.replaceAll('_',' ').toLowerCase()}</li>)}{readiness.ready && <li>Local readiness checks complete</li>}</ul>{canEdit && <Button onClick={() => void onValidateIssue().then(result => { if (!result.ready) { setMessage(result.codes.join(', ')); return; } return onIssue({ title: `Specification issue ${workspace.revision}`, audience: 'Project team' }).then(() => setMessage('Issue created and distributed to configured destinations.')); }).catch(error => setMessage(error instanceof Error ? error.message : 'Issue failed.'))}>Validate and issue {workspace.revision}</Button>}{message && <small role="status">{message}</small>}</Surface></div>;

  return <Empty title="Workspace view unavailable" detail="Choose a SpecForge workflow tab." />;
}

function Empty({ title, detail }: { title: string; detail: string }) { return <Surface level="inset" className="specforge-empty"><h2>{title}</h2><p>{detail}</p></Surface>; }
